### ISSUE TITLE
Test Support for Dedup and Title

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther_analysis_tool#18]
## Description

Currently, the `panther_analysis_tool` only validates the rule function. To ensure that our deduplication and title generation works properly, we should add checks to make sure `None` is not returned.

**Comment by kostaspap** [comment]
My idea is that the Analysis Tool should just invoke the necessary API in the Panther backend. Few reasons: 
1. We are basically trying to duplicate the rules-engine functionality in a CLI tool. It is very likely the two will become out of sync as new features get added to the rules engine. 
2. Panther deployment has access to different resources than a workstation. A rule that passes successfully on a laptop can fail in Panther and vice versa. CLI should be just a more "handy" version to run the rules through the Panther UI, not a different system. 

I don't know what's the effort involved in that, but I'd much rather modify the Analysis tool to just use Panther installation to run the rules. The tool anyway requires connectivity with Panther in order to upload the rules in bulk.

**Comment by nhakmiller** [comment]
We now print out the title and dedup strings as part of the test. This is nice for manual verification, but does not handle automatic testing well. Do you feel like this meets your needs @jacknagz , or do you think we should add automatic testing for dedup and title functions? (e.g. a field in the unit test indicating what should be returned by the dedup/title functions)

**Comment by jacknagz** [comment]
@nhakmiller I think we just want to verify that `None` was not returned if these functions are defined
